
target 'SynqUploader_Example' do
  pod 'SynqUploader', :path => '../'

  target 'SynqUploader_Tests' do
    inherit! :search_paths
    
  end

  target 'SynqUploader_ExampleUITests' do
    inherit! :search_paths
    pod 'SynqUploader', :path => '../'

  end
end
